package Entidades;

public enum TipoUva {
    CABERNET_SAUVIGNON, MERLOT, TEMPRANILLO, GARNACHA, PINOT_NOIR, BONARDA, PINOT_GRIS, CHARDONNAY, SAUVIGNON_BLANC, VERDEJO, ALBARIÑO, GODELLO, MALBEC, MOSCATEL_ALEJANDRIA, CABERNET_FRANC
}
